= log-timbre

A short template on the use of Timbre for Clojure logging

== Usage

Just execute using lein:

    > lein run
    Hello, World!
    Shutting down...

    > cat log.txt
    2014-Oct-30 23:00:11 -0700 localhost.localdomain INFO [log-timbre.core] - Hello, Timbre! info
    2014-Oct-30 23:00:11 -0700 localhost.localdomain INFO [log-timbre.core] - Hello, Timbre! spy :info Hello, Timbre! spy :info
    2014-Oct-30 23:00:11 -0700 localhost.localdomain DEBUG [log-timbre.core] - Hello, Timbre! debug
    2014-Oct-30 23:00:11 -0700 localhost.localdomain INFO [log-timbre.core] - arg2 arg3
    java.lang.Exception: Doh!
             log-timbre.core/-main                          core.clj:   36
        clojure.lang.RestFn.invoke                       RestFn.java:  397
           clojure.lang.Var.invoke                          Var.java:  375
                        user/eval3  form-init6280606650468310964.clj:    1
        clojure.lang.Compiler.eval                     Compiler.java: 6767
        clojure.lang.Compiler.eval                     Compiler.java: 6757
        clojure.lang.Compiler.load                     Compiler.java: 7194
    clojure.lang.Compiler.loadFile                     Compiler.java: 7150
          clojure.main/load-script                          main.clj:  274
             clojure.main/init-opt                          main.clj:  279
           clojure.main/initialize                          main.clj:  307
             clojure.main/null-opt                          main.clj:  342
                 clojure.main/main                          main.clj:  420
        clojure.lang.RestFn.invoke                       RestFn.java:  421
           clojure.lang.Var.invoke                          Var.java:  383
    clojure.lang.AFn.applyToHelper                          AFn.java:  156
          clojure.lang.Var.applyTo                          Var.java:  700
                 clojure.main.main                         main.java:   37

    2014-Oct-30 23:00:12 -0700 localhost.localdomain INFO [log-timbre.core] - (my-fn) =>  42
    2014-Oct-30 23:00:12 -0700 localhost.localdomain INFO [log-timbre.core] - Profiling: :log-timbre.core/Arithmetic
                             Id      nCalls       Min        Max       MAD      Mean   Time% Time
    :log-timbre.core/slow-sleep         100     2.0ms      5.0ms    99.0μs     2.0ms      47 213.0ms
    :log-timbre.core/fast-sleep         100     1.0ms      5.0ms    79.0μs     1.0ms      24 111.0ms
           :log-timbre.core/div         100    68.0μs      1.0ms    85.0μs   234.0μs       5 23.0ms
          :log-timbre.core/mult         100    42.0μs    544.0μs    54.0μs   149.0μs       3 15.0ms
           :log-timbre.core/sub         100    43.0μs    464.0μs    59.0μs   143.0μs       3 14.0ms
           :log-timbre.core/add         100    55.0μs    379.0μs    45.0μs   136.0μs       3 14.0ms
                     Clock Time                                                          100 457.0ms
                 Accounted Time                                                           85 390.0ms



== The source code says everything you need to know:

[source,clojure]
----
(ns demo-timbre.core
  (:require [clojure.java.io :as io]
            [taoensso.timbre :as timbre] )
  (:gen-class))

(def log-file-name "log.txt")
(io/delete-file log-file-name :quiet)

(timbre/refer-timbre) ; set up timbre aliases
(timbre/set-config! [:appenders :standard-out   :enabled?] false)   ; turn off console logging
(timbre/set-config! [:appenders :spit           :enabled?] true)    ; turn on file logging
(timbre/set-config! [:shared-appender-config :spit-filename] log-file-name) ; output filename

(defn my-fn
  []
  (let [nums (vec (range 1000))]
    (+ (p :fast-sleep (Thread/sleep 1) 10)
       (p :slow-sleep (Thread/sleep 2) 32)
       (p :add  (reduce + nums))
       (p :sub  (reduce - nums))
       (p :mult (reduce * nums))
       (p :div  (reduce / nums)))))

(defn -main []
  (println "Hello, World!")  ; a short message to the console

  ; Demonstrate logging with Timbre
  (info "Hello, Timbre! info")
  (spy :info "Hello, Timbre! spy :info")
  (debug "Hello, Timbre! debug")
  (trace "Hello, Timbre! trace")

  ; Even exceptions look nice in the logs
  (info (Exception. "Doh!") "arg2" "arg3")

  ; Demonstrate profiling with Timbre
  (info "(my-fn) => " (my-fn))
  (profile :info :Arithmetic (dotimes [n 100] (my-fn)))

  ; If this is omitted there is a one minute delay before (non-daemon) agent 
  ; threads will shutdown
  (println "Shutting down...")
  (shutdown-agents) 
)
----

== License

Copyright © 2014 Alan Thompson

Distributed under the Eclipse Public License either version 1.0 or (at
your option) any later version.
